version = 1

exclude_patterns = [
    "noren_wallet/migrations/**",
    "noren_auth/migrations/**"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["jquery"]
  style_guide = "google"
  dialect = "flow"
